# Pandas Practice Test 1

This notebook contains a customer dataset and 25 practice questions designed to test your `pandas` skills across basic exploration, data cleaning, filtering, sorting, and grouping.

## Dataset Setup
Run the cell below to load the customer dataset into a pandas DataFrame named `df`.

In [28]:
import pandas as pd

---

In [29]:
df = pd.read_csv("data.csv")
df

,CustomerID,Name,City,Age,TotalSpend,OrdersCount,FavCategory,PreferredPayment,DiscountUsed
0,101,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes
1,102,Ananya Patel,Ahmedabad,34,12500.0,4,Clothing,UPI,No
2,103,Rohan Mehta,Surat,22,8900.0,3,Books,UPI,Yes
3,104,Priya Singh,Mumbai,45,67000.0,20,Electronics,Credit Card,No
4,105,Dev Varma,Surat,29,NaN,8,Home & Kitchen,Debit Card,Yes
5,106,Isha Joshi,Ahmedabad,25,3100.0,1,Books,NaN,No
6,107,Karan Shah,Surat,31,24000.0,6,Electronics,UPI,Yes
7,108,Sanya Kapadia,Mumbai,19,4200.0,2,Clothing,Debit Card,No
8,109,Vikram Malhotra,Delhi,52,98000.0,25,Electronics,Credit Card,Yes
9,110,Neha Gupta,Surat,28,15600.0,5,Home & Kitchen,UPI,NaN
10,111,Rahul Nair,Bengaluru,38,51000.0,14,Electronics,Credit Card,Yes
11,112,Pooja Trivedi,Ahmedabad,29,7200.0,3,Books,UPI,No
12,113,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes
13,114,Manish Kumar,Delhi,41,NaN,11,Home & Kitchen,Debit Card,No
14,115,Riya Desai,Surat,24,18900.0,7,Clothing,UPI,Yes

### 🟢 Level 1 — Basic Exploration

#### Q1. How many total rows and columns are in the dataset?

In [30]:
# Write your code here
print(f"There are {df.shape[0]} columns in the dataset")
print(f"There are {df.shape[1]} rows in the dataset")

There are 15 columns in the dataset
There are 9 rows in the dataset

#### Q2. Display all column names and their data types.

In [31]:
# Write your code here
df.dtypes

CustomerID            int64
Name                    str
City                    str
Age                   int64
TotalSpend          float64
OrdersCount           int64
FavCategory             str
PreferredPayment        str
DiscountUsed            str
dtype: object

#### Q3. Find the total number of missing (`null`) values in the dataset overall and per column.

In [32]:
# Write your code here
print(df.isnull().sum(True).sum())
print(df.isnull().sum())

4
CustomerID          0
Name                0
City                0
Age                 0
TotalSpend          2
OrdersCount         0
FavCategory         0
PreferredPayment    1
DiscountUsed        1
dtype: int64

C:\Users\DELL\AppData\Local\Temp\ipykernel_11604\1157756268.py:2: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  print(df.isnull().sum(True).sum())

#### Q4. List all unique cities and unique product categories present in the data.

In [33]:
# Write your code here
UniqueCities = list(df["City"].unique())
print(UniqueCities)
UniqueProduct = list(df["FavCategory"].unique())
print(UniqueProduct)

['Surat', 'Ahmedabad', 'Mumbai', 'Delhi', 'Bengaluru']
['Electronics', 'Clothing', 'Books', 'Home & Kitchen']

#### Q5. Check if there are any duplicate rows in the dataset.

In [34]:
# Write your code here
print(df.duplicated().sum())

0

---

### 🟡 Level 2 — Data Cleaning & Manipulation

#### Q6. Fill all missing values in `TotalSpend` with the column's mean value.

In [35]:
# Write your code here
df["TotalSpend"].fillna(df["TotalSpend"].mean())

0     45000.0
1     12500.0
2      8900.0
3     67000.0
4     30800.0
5      3100.0
6     24000.0
7      4200.0
8     98000.0
9     15600.0
10    51000.0
11     7200.0
12    45000.0
13    30800.0
14    18900.0
Name: TotalSpend, dtype: float64

#### Q7. Fill all missing values in `PreferredPayment` with `"Unknown"`.

In [36]:
# Write your code here
df["PreferredPayment"].fillna("Unknown")

0     Credit Card
1             UPI
2             UPI
3     Credit Card
4      Debit Card
5         Unknown
6             UPI
7      Debit Card
8     Credit Card
9             UPI
10    Credit Card
11            UPI
12    Credit Card
13     Debit Card
14            UPI
Name: PreferredPayment, dtype: str

#### Q8. Remove any exact duplicate rows from the DataFrame.

In [37]:
# Write your code here
df.drop_duplicates()

,CustomerID,Name,City,Age,TotalSpend,OrdersCount,FavCategory,PreferredPayment,DiscountUsed
0,101,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes
1,102,Ananya Patel,Ahmedabad,34,12500.0,4,Clothing,UPI,No
2,103,Rohan Mehta,Surat,22,8900.0,3,Books,UPI,Yes
3,104,Priya Singh,Mumbai,45,67000.0,20,Electronics,Credit Card,No
4,105,Dev Varma,Surat,29,NaN,8,Home & Kitchen,Debit Card,Yes
5,106,Isha Joshi,Ahmedabad,25,3100.0,1,Books,NaN,No
6,107,Karan Shah,Surat,31,24000.0,6,Electronics,UPI,Yes
7,108,Sanya Kapadia,Mumbai,19,4200.0,2,Clothing,Debit Card,No
8,109,Vikram Malhotra,Delhi,52,98000.0,25,Electronics,Credit Card,Yes
9,110,Neha Gupta,Surat,28,15600.0,5,Home & Kitchen,UPI,NaN
10,111,Rahul Nair,Bengaluru,38,51000.0,14,Electronics,Credit Card,Yes
11,112,Pooja Trivedi,Ahmedabad,29,7200.0,3,Books,UPI,No
12,113,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes
13,114,Manish Kumar,Delhi,41,NaN,11,Home & Kitchen,Debit Card,No
14,115,Riya Desai,Surat,24,18900.0,7,Clothing,UPI,Yes

#### Q9. Rename the column `OrdersCount` to `TotalOrders`.

In [38]:
# Write your code here
df.rename(columns={"OrdersCount":"TotalOrders"}, inplace=True)
print(df)

    CustomerID             Name       City  Age  TotalSpend  TotalOrders  \
0          101     Aarav Sharma      Surat   28     45000.0           12
1          102     Ananya Patel  Ahmedabad   34     12500.0            4
2          103      Rohan Mehta      Surat   22      8900.0            3
3          104      Priya Singh     Mumbai   45     67000.0           20
4          105        Dev Varma      Surat   29         NaN            8
5          106       Isha Joshi  Ahmedabad   25      3100.0            1
6          107       Karan Shah      Surat   31     24000.0            6
7          108    Sanya Kapadia     Mumbai   19      4200.0            2
8          109  Vikram Malhotra      Delhi   52     98000.0           25
9          110       Neha Gupta      Surat   28     15600.0            5
10         111       Rahul Nair  Bengaluru   38     51000.0           14
11         112    Pooja Trivedi  Ahmedabad   29      7200.0            3
12         113     Aarav Sharma      Surat   28     45000.0           12
13         114     Manish Kumar      Delhi   41         NaN           11
14         115       Riya Desai      Surat   24     18900.0            7

       FavCategory PreferredPayment DiscountUsed
0      Electronics      Credit Card          Yes
1         Clothing              UPI           No
2            Books              UPI          Yes
3      Electronics      Credit Card           No
4   Home & Kitchen       Debit Card          Yes
5            Books              NaN           No
6      Electronics              UPI          Yes
7         Clothing       Debit Card           No
8      Electronics      Credit Card          Yes
9   Home & Kitchen              UPI          NaN
10     Electronics      Credit Card          Yes
11           Books              UPI           No
12     Electronics      Credit Card          Yes
13  Home & Kitchen       Debit Card           No
14        Clothing              UPI          Yes

#### Q10. Drop all rows where `PreferredPayment` is missing or unknown.

In [64]:
# Write your code here
df2 = df["PreferredPayment"].dropna()
print(df2)

0     Credit Card
1             UPI
2             UPI
3     Credit Card
4      Debit Card
6             UPI
7      Debit Card
8     Credit Card
9             UPI
10    Credit Card
11            UPI
12    Credit Card
13     Debit Card
14            UPI
Name: PreferredPayment, dtype: str

---

### 🟠 Level 3 — Filtering & Conditional Logic

#### Q11. Find all customers from **Surat**.

In [ ]:
# Write your code here
CustomersSurat = df[df["City"] == "Surat"]
CustomersSurat

    CustomerID          Name   City  Age  TotalSpend  TotalOrders  \
0          101  Aarav Sharma  Surat   28     45000.0           12
2          103   Rohan Mehta  Surat   22      8900.0            3
4          105     Dev Varma  Surat   29         NaN            8
6          107    Karan Shah  Surat   31     24000.0            6
9          110    Neha Gupta  Surat   28     15600.0            5
12         113  Aarav Sharma  Surat   28     45000.0           12
14         115    Riya Desai  Surat   24     18900.0            7

       FavCategory PreferredPayment DiscountUsed
0      Electronics      Credit Card          Yes
2            Books              UPI          Yes
4   Home & Kitchen       Debit Card          Yes
6      Electronics              UPI          Yes
9   Home & Kitchen              UPI          NaN
12     Electronics      Credit Card          Yes
14        Clothing              UPI          Yes

#### Q12. Find all customers who spent more than **₹20,000** (`TotalSpend > 20000`).

In [69]:
# Write your code here
Spent20 = df[df["TotalSpend"] > 20000]
Spent20

,CustomerID,Name,City,Age,TotalSpend,TotalOrders,FavCategory,PreferredPayment,DiscountUsed
0,101,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes
3,104,Priya Singh,Mumbai,45,67000.0,20,Electronics,Credit Card,No
6,107,Karan Shah,Surat,31,24000.0,6,Electronics,UPI,Yes
8,109,Vikram Malhotra,Delhi,52,98000.0,25,Electronics,Credit Card,Yes
10,111,Rahul Nair,Bengaluru,38,51000.0,14,Electronics,Credit Card,Yes
12,113,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes

#### Q13. Find customers who are from **Surat** AND use **UPI** as their preferred payment method.

In [73]:
# Write your code here
SuratUPI = df[(df["City"] == "Surat") & (df["PreferredPayment"] == "UPI")]
SuratUPI

,CustomerID,Name,City,Age,TotalSpend,TotalOrders,FavCategory,PreferredPayment,DiscountUsed
2,103,Rohan Mehta,Surat,22,8900.0,3,Books,UPI,Yes
6,107,Karan Shah,Surat,31,24000.0,6,Electronics,UPI,Yes
9,110,Neha Gupta,Surat,28,15600.0,5,Home & Kitchen,UPI,NaN
14,115,Riya Desai,Surat,24,18900.0,7,Clothing,UPI,Yes

#### Q14. Find customers whose `Age` is between **25 and 35** (inclusive).

In [72]:
# Write your code here
Age25_35 = df[df["Age"].between(25,35)]
Age25_35

,CustomerID,Name,City,Age,TotalSpend,TotalOrders,FavCategory,PreferredPayment,DiscountUsed
0,101,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes
1,102,Ananya Patel,Ahmedabad,34,12500.0,4,Clothing,UPI,No
4,105,Dev Varma,Surat,29,NaN,8,Home & Kitchen,Debit Card,Yes
5,106,Isha Joshi,Ahmedabad,25,3100.0,1,Books,NaN,No
6,107,Karan Shah,Surat,31,24000.0,6,Electronics,UPI,Yes
9,110,Neha Gupta,Surat,28,15600.0,5,Home & Kitchen,UPI,NaN
11,112,Pooja Trivedi,Ahmedabad,29,7200.0,3,Books,UPI,No
12,113,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes

#### Q15. Find customers who used a discount (`DiscountUsed == 'Yes'`) OR whose `TotalSpend` is greater than **₹50,000**.

In [74]:
# Write your code here
Customers = df[(df["DiscountUsed"] == "Yes") | (df["TotalSpend"] > 50000)]
Customers

,CustomerID,Name,City,Age,TotalSpend,TotalOrders,FavCategory,PreferredPayment,DiscountUsed
0,101,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes
2,103,Rohan Mehta,Surat,22,8900.0,3,Books,UPI,Yes
3,104,Priya Singh,Mumbai,45,67000.0,20,Electronics,Credit Card,No
4,105,Dev Varma,Surat,29,NaN,8,Home & Kitchen,Debit Card,Yes
6,107,Karan Shah,Surat,31,24000.0,6,Electronics,UPI,Yes
8,109,Vikram Malhotra,Delhi,52,98000.0,25,Electronics,Credit Card,Yes
10,111,Rahul Nair,Bengaluru,38,51000.0,14,Electronics,Credit Card,Yes
12,113,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes
14,115,Riya Desai,Surat,24,18900.0,7,Clothing,UPI,Yes

---

### 🔵 Level 4 — Sorting & Aggregation

#### Q16. Find the maximum, minimum, and average `TotalSpend` across all customers.

In [78]:
# Write your code here
print(df["TotalSpend"].max())
print(df["TotalSpend"].min())
print(df["TotalSpend"].mean())

98000.0
3100.0
30800.0

#### Q17. Sort the dataset by `TotalSpend` in descending order.

In [81]:
# Write your code here
sortdata = df.sort_values("TotalSpend",ascending=False)
sortdata

,CustomerID,Name,City,Age,TotalSpend,TotalOrders,FavCategory,PreferredPayment,DiscountUsed
8,109,Vikram Malhotra,Delhi,52,98000.0,25,Electronics,Credit Card,Yes
3,104,Priya Singh,Mumbai,45,67000.0,20,Electronics,Credit Card,No
10,111,Rahul Nair,Bengaluru,38,51000.0,14,Electronics,Credit Card,Yes
0,101,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes
12,113,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes
6,107,Karan Shah,Surat,31,24000.0,6,Electronics,UPI,Yes
14,115,Riya Desai,Surat,24,18900.0,7,Clothing,UPI,Yes
9,110,Neha Gupta,Surat,28,15600.0,5,Home & Kitchen,UPI,NaN
1,102,Ananya Patel,Ahmedabad,34,12500.0,4,Clothing,UPI,No
2,103,Rohan Mehta,Surat,22,8900.0,3,Books,UPI,Yes
11,112,Pooja Trivedi,Ahmedabad,29,7200.0,3,Books,UPI,No
7,108,Sanya Kapadia,Mumbai,19,4200.0,2,Clothing,Debit Card,No
5,106,Isha Joshi,Ahmedabad,25,3100.0,1,Books,NaN,No
4,105,Dev Varma,Surat,29,NaN,8,Home & Kitchen,Debit Card,Yes
13,114,Manish Kumar,Delhi,41,NaN,11,Home & Kitchen,Debit Card,No

#### Q18. Find the top 3 highest-spending customers.

In [82]:
# Write your code here
sortdata.head(3)

,CustomerID,Name,City,Age,TotalSpend,TotalOrders,FavCategory,PreferredPayment,DiscountUsed
8,109,Vikram Malhotra,Delhi,52,98000.0,25,Electronics,Credit Card,Yes
3,104,Priya Singh,Mumbai,45,67000.0,20,Electronics,Credit Card,No
10,111,Rahul Nair,Bengaluru,38,51000.0,14,Electronics,Credit Card,Yes

#### Q19. Find the average age of customers who use **Credit Card**.

In [84]:
# Write your code here
CreditCardCustomer = df[df["PreferredPayment"] == "Credit Card"]
print(CreditCardCustomer["Age"].mean())

38.2

#### Q20. Calculate the total number of orders across all customers combined.

In [85]:
# Write your code here
print(df["TotalOrders"].sum())

133

---

### 🟣 Level 5 — GroupBy & Advanced Analytics

#### Q21. Find the total count of customers in each `City`.

In [93]:
# Write your code here
df["City"].value_counts()

City
Surat        7
Ahmedabad    3
Mumbai       2
Delhi        2
Bengaluru    1
Name: count, dtype: int64

#### Q22. Calculate the average `TotalSpend` for each `FavCategory`.

In [99]:
# Write your code here
FavCatdf = df.groupby("FavCategory")
FavCatdf["TotalSpend"].mean()

FavCategory
Books              6400.000000
Clothing          11866.666667
Electronics       55000.000000
Home & Kitchen    15600.000000
Name: TotalSpend, dtype: float64

#### Q23. Find the maximum `TotalSpend` achieved in each `PreferredPayment` method group.

In [100]:
# Write your code here
PPdf = df.groupby("PreferredPayment")
PPdf["TotalSpend"].max()

PreferredPayment
Credit Card    98000.0
Debit Card      4200.0
UPI            24000.0
Name: TotalSpend, dtype: float64

#### Q24. Determine which city has the highest overall average customer spending.

In [ ]:
# Write your code here
citydf = df.groupby("City")
print(f"{citydf["TotalSpend"].mean().idxmax()} : {citydf["TotalSpend"].mean().max()}")

Delhi 98000.0

#### Q25. Find all customers who have a `TotalSpend` higher than the overall average spend of the entire dataset.

In [105]:
# Write your code here
avgspend = df["TotalSpend"].mean()
HighCustomer = df[df["TotalSpend"] > avgspend]
HighCustomer

,CustomerID,Name,City,Age,TotalSpend,TotalOrders,FavCategory,PreferredPayment,DiscountUsed
0,101,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes
3,104,Priya Singh,Mumbai,45,67000.0,20,Electronics,Credit Card,No
8,109,Vikram Malhotra,Delhi,52,98000.0,25,Electronics,Credit Card,Yes
10,111,Rahul Nair,Bengaluru,38,51000.0,14,Electronics,Credit Card,Yes
12,113,Aarav Sharma,Surat,28,45000.0,12,Electronics,Credit Card,Yes